### ISSUE TITLE
Growth is not showing up on Pokemon in Hunt Menu.

### ISSUE THREAD

**Issue by speccycy** [Daniel-Forge-Development/PixelHuntRemastered#1]
I set require-growth to true, but this information is not displayed in Pokemon.

PixelHuntRemastered-Forge Ver.0.7.0

![image](https://user-images.githubusercontent.com/68125477/136842287-ac67dc3d-7779-41cb-bd9c-516262eeac66.png)

```
Expert-2:
        gui:
            X: 7
            Y: 3
        random-reward-commands: true
        reward-commands:
        - minecraft:give %player% pixelmon:dynamax_candy 1
        - minecraft:give %player% pixelmon:xl_exp_candy 4
        - minecraft:give %player% pixelmon:xl_exp_candy 6
        - minecraft:give %player% pixelmon:xl_exp_cand 8
        require-species: true
        allow-legends: false
        allow-ultra-beasts: true
        allow-evolutions: false
        require-gender: true
        require-growth: true
        numer-of-possible-growths: 2
        require-nature: true
        number-of-possible-natures: 2
        require-iv-percentage: true
        random-iv-generation: true
        minimum-iv-percentage: 30
        maximum-iv-percentage: 100
        max-ivs: false
        iv-multiplier-enabled: true
        iv-multiplier: 1.5
        max-duration-minutes: 120

```
